<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd10fec1d5e2f1b8cd4e5764fd9901d69
{
    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'cweagans\\Composer\\' => 18,
        ),
        'R' => 
        array (
            'Respect\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'cweagans\\Composer\\' => 
        array (
            0 => __DIR__ . '/..' . '/cweagans/composer-patches/src',
        ),
        'Respect\\' => 
        array (
            0 => __DIR__ . '/..' . '/respect/rest/library/Respect',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd10fec1d5e2f1b8cd4e5764fd9901d69::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd10fec1d5e2f1b8cd4e5764fd9901d69::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd10fec1d5e2f1b8cd4e5764fd9901d69::$classMap;

        }, null, ClassLoader::class);
    }
}
