<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Respect\\Rest\\Request' => $vendorDir . '/respect/rest/library/Respect/Rest/Request.php',
    'Respect\\Rest\\Routable' => $vendorDir . '/respect/rest/library/Respect/Rest/Routable.php',
    'Respect\\Rest\\Router' => $vendorDir . '/respect/rest/library/Respect/Rest/Router.php',
    'Respect\\Rest\\Routes\\AbstractRoute' => $vendorDir . '/respect/rest/library/Respect/Rest/Routes/AbstractRoute.php',
    'Respect\\Rest\\Routes\\Callback' => $vendorDir . '/respect/rest/library/Respect/Rest/Routes/Callback.php',
    'Respect\\Rest\\Routes\\ClassName' => $vendorDir . '/respect/rest/library/Respect/Rest/Routes/ClassName.php',
    'Respect\\Rest\\Routes\\Error' => $vendorDir . '/respect/rest/library/Respect/Rest/Routes/Error.php',
    'Respect\\Rest\\Routes\\Exception' => $vendorDir . '/respect/rest/library/Respect/Rest/Routes/Exception.php',
    'Respect\\Rest\\Routes\\Factory' => $vendorDir . '/respect/rest/library/Respect/Rest/Routes/Factory.php',
    'Respect\\Rest\\Routes\\Instance' => $vendorDir . '/respect/rest/library/Respect/Rest/Routes/Instance.php',
    'Respect\\Rest\\Routes\\StaticValue' => $vendorDir . '/respect/rest/library/Respect/Rest/Routes/StaticValue.php',
    'Respect\\Rest\\Routines\\AbstractAccept' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/AbstractAccept.php',
    'Respect\\Rest\\Routines\\AbstractCallbackList' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/AbstractCallbackList.php',
    'Respect\\Rest\\Routines\\AbstractCallbackMediator' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/AbstractCallbackMediator.php',
    'Respect\\Rest\\Routines\\AbstractRoutine' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/AbstractRoutine.php',
    'Respect\\Rest\\Routines\\AbstractSyncedRoutine' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/AbstractSyncedRoutine.php',
    'Respect\\Rest\\Routines\\Accept' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/Accept.php',
    'Respect\\Rest\\Routines\\AcceptCharset' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/AcceptCharset.php',
    'Respect\\Rest\\Routines\\AcceptEncoding' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/AcceptEncoding.php',
    'Respect\\Rest\\Routines\\AcceptLanguage' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/AcceptLanguage.php',
    'Respect\\Rest\\Routines\\AuthBasic' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/AuthBasic.php',
    'Respect\\Rest\\Routines\\By' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/By.php',
    'Respect\\Rest\\Routines\\ContentType' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/ContentType.php',
    'Respect\\Rest\\Routines\\IgnorableFileExtension' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/IgnorableFileExtension.php',
    'Respect\\Rest\\Routines\\LastModified' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/LastModified.php',
    'Respect\\Rest\\Routines\\ParamSynced' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/ParamSynced.php',
    'Respect\\Rest\\Routines\\ProxyableBy' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/ProxyableBy.php',
    'Respect\\Rest\\Routines\\ProxyableThrough' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/ProxyableThrough.php',
    'Respect\\Rest\\Routines\\ProxyableWhen' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/ProxyableWhen.php',
    'Respect\\Rest\\Routines\\Rel' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/Rel.php',
    'Respect\\Rest\\Routines\\Routinable' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/Routinable.php',
    'Respect\\Rest\\Routines\\Through' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/Through.php',
    'Respect\\Rest\\Routines\\Unique' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/Unique.php',
    'Respect\\Rest\\Routines\\UserAgent' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/UserAgent.php',
    'Respect\\Rest\\Routines\\When' => $vendorDir . '/respect/rest/library/Respect/Rest/Routines/When.php',
);
